### ISSUE TITLE
Socket automatic recovery

### ISSUE THREAD

**Issue by jonathanleang** [Mazyod/PhoenixSharp#4]
how important is this ?

**Comment by Mazyod** [comment]
@jonathanleang it's just an enhancement. Currently, if the socket connection closes because of an error, it doesn't automatically attempt to reconnect for you. You have to handle the error, and reconnect manually.

In my project, I use a FSM to manage the socket state, so I don't need the library to handle recovery for me.

**Comment by jonathanleang** [comment]
Thanks for creating this project !
