### ISSUE TITLE
Why targetting .NET Framework 3.0?

### ISSUE THREAD

**Issue by MissaouiChedy** [Mazyod/PhoenixSharp#7]
I would like to know why the project is targeting .NET 3.0? Is it for Unity compatibility reasons?

@Mazyod What do you think about a migration to net-standard 2.0? Would it be acceptable with regard to Unity Compatibility?

**Comment by Mazyod** [comment]
Yes, Unity compatibility is a top priority for this project, as mentioned in the goals. Unity currently ships with an experimental .NET 4.6 profile, but it's still buggy.

I don't think net-standard is even within the horizon for Unity (2+ years at least).

Either way, I totally sympathize with the problem here, and all I can offer is to try and make the core engine here as compatible as possible with possible wrappers that provide enhanced APIs for the versions you are mentioning, since I am guessing they are supersets of .NET 3.0

**Comment by Mazyod** [comment]
I realized I haven't mentioned the goals here, but did that in the elixir forums! Will migrate those over

**Comment by MissaouiChedy** [comment]
OK, Thank you.
